services:
  _defaults:
    autowire: true
    public: false

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: FreshAdvance\OxidEventDebugger\Event\Dispatcher
    public: true
    arguments:
      'Psr\Log\LoggerInterface': '@FreshAdvance\OxidEventDebugger\Logger'

  FreshAdvance\OxidEventDebugger\Logger:
    class: Monolog\Logger
    factory: 'FreshAdvance\OxidEventDebugger\Logger\Factory:create'

  FreshAdvance\OxidEventDebugger\Logger\Factory:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Factory\MonologLoggerFactory
    arguments:
      'OxidEsales\EshopCommunity\Internal\Framework\Logger\Configuration\MonologConfigurationInterface': '@FreshAdvance\OxidEventDebugger\Logger\Configuration'

  FreshAdvance\OxidEventDebugger\Logger\Configuration:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Configuration\MonologConfiguration
    arguments:
      $loggerName: 'Event Logger'
      $logFilePath: '@utility.context.events_log_file_path'
      $logLevel: !php/const Psr\Log\LogLevel::DEBUG

  utility.context.events_log_file_path:
    class: FreshAdvance\OxidEventDebugger\Utility\Context
    factory: FreshAdvance\OxidEventDebugger\Utility\Context:getEventsLogFilePath

  FreshAdvance\OxidEventDebugger\Utility\Context:
    class: FreshAdvance\OxidEventDebugger\Utility\Context
